name: Tag Version

on:
  workflow_run:
    workflows: ["Unit test"]
    branches:
      - 'main'
    types:
      - completed

jobs:
  tag_version:
    # run job if previous was successful
    # don`t run if commit message starts with '[RELEASE]' to prevent infinite loop
    if: ${{ github.event.workflow_run.conclusion == 'success' && !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    name: tag version
    uses: swiss-code/common_workflows/.github/workflows/gradle-tag-version.yml@main
    with:
      gradle_location: lib/build.gradle
    secrets:
      checkout_token: ${{ secrets.NHPHUOC_GITHUB_ACTION_SECRET }}
